name = "ego-money"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "ego"
database_id = "efd88bbb-8dca-4164-b3e5-b8040572551e"
migrations_dir = "migrations"
